# Generated by Django 4.2.4 on 2023-11-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Acc',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Email_id', models.CharField(default='', max_length=200, unique=True)),
                ('Mobile', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
